// lovelytools.ai — audience collections (RFC-001 §2, DS §9 "Curated for how you work").
// Cross-category curated sets targeting audience intent ("tools for students").
// Every slug is validated against the tool set by registry:check.
import type { Collection } from './types';

export const COLLECTIONS: Collection[] = [
  {
    slug: 'student-tools',
    name: 'Student',
    label: 'For students',
    description: 'Essays, citations, unit math',
    hue: '#38BDF8',
    tools: [
      'word-counter',
      'merge-pdf',
      'compress-pdf',
      'pdf-to-word',
      'gpa-calculator',
      'percentage-calculator',
      'case-converter',
      'length-converter',
      'image-compressor',
      'pdf-to-text',
    ],
  },
  {
    slug: 'business-tools',
    name: 'Business',
    label: 'For business',
    description: 'Contracts, decks, invoices',
    hue: '#7C6CFF',
    tools: [
      'sign-pdf',
      'merge-pdf',
      'pdf-to-word',
      'word-to-pdf',
      'excel-to-pdf',
      'powerpoint-to-pdf',
      'compress-pdf',
      'protect-pdf',
      'add-watermark-pdf',
      'loan-calculator',
    ],
  },
  {
    slug: 'marketing-tools',
    name: 'Marketing',
    label: 'For marketers',
    description: 'Assets, compression, copy',
    hue: '#FF8A3D',
    tools: [
      'image-compressor',
      'resize-image',
      'remove-background',
      'jpg-to-webp',
      'png-to-webp',
      'crop-image',
      'word-counter',
      'case-converter',
      'compress-video',
      'mp4-to-gif',
    ],
  },
  {
    slug: 'designer-tools',
    name: 'Designer',
    label: 'For designers',
    description: 'Formats, palettes, exports',
    hue: '#F472B6',
    tools: [
      'svg-to-png',
      'resize-image',
      'crop-image',
      'remove-background',
      'color-converter',
      'image-compressor',
      'heic-to-jpg',
      'png-to-jpg',
      'image-to-pdf',
      'rotate-image',
    ],
  },
  {
    slug: 'finance-tools',
    name: 'Finance',
    label: 'For finance',
    description: 'Loans, rates, statements',
    hue: '#4ADE80',
    tools: [
      'loan-calculator',
      'mortgage-calculator',
      'compound-interest-calculator',
      'percentage-calculator',
      'vat-calculator',
      'currency-converter',
      'pdf-to-excel',
      'excel-to-pdf',
      'tip-calculator',
      'salary-calculator',
    ],
  },
  {
    slug: 'creator-tools',
    name: 'Content Creator',
    label: 'For creators',
    description: 'Clips, thumbnails, audio',
    hue: '#FFC53D',
    tools: [
      'trim-video',
      'compress-video',
      'mp4-to-gif',
      'video-to-mp3',
      'resize-image',
      'crop-image',
      'trim-audio',
      'compress-audio',
      'mp3-converter',
      'remove-background',
      'video-subtitle-generator',
      'video-url-to-audio',
    ],
  },
  {
    slug: 'developer-kit',
    name: 'Developer',
    label: 'For developers',
    description: 'JSON, JWT, regex, SQL',
    hue: '#34D3C3',
    tools: [
      'json-formatter',
      'jwt-decoder',
      'regex-tester',
      'base64-encode',
      'url-encoder',
      'uuid-generator',
      'hash-generator',
      'timestamp-converter',
      'sql-formatter',
      'color-converter',
    ],
  },
];
